CREATE TABLE JOBS IF NOT EXISTS(
    JOB_ID INT PRIMARY KEY,
    JOB_NUMBER TEXT UNIQUE NOT NULL,
)

CREATE TABLE GENOMEMAP_INFO IF NOT EXISTS(
    JOB_NUMBER TEXT PRIMARY KEY,
    DATUM TEXT NOT NULL,
    FOREIGN KEY (JOB_NUMBER) REFERENCES JOBS (JOB_NUMBER),
)